sudo: required
services:
  - docker

env:
  COMPOSE_VERSION=1.20.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - chmod +x envvars-to-secrets.sh
 - ./envvars-to-secrets.sh

script:
  - docker-compose build
  - docker-compose up -d

notifications:
  email: false