version: '3.1'

services:

  mysql:
    image: mysql:5.7
    secrets:
      - mysql-root-password
    volumes:
      - ./services/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      # see docker secrets section at https://hub.docker.com/_/mysql/
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: pf_dev

  shiny:
    build: ./shiny-server/pfapp
    secrets:
      - mysql-root-password
    volumes:
      - ./services/conf/shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - ./shiny-server/pfapp:/srv/shiny-server/pfapp
    restart: always

  pfproto:
    depends_on:
      - mysql
    build: ./prototype/pfproto
    ports:
      - 8780:8787
    secrets:
      - pf-key
      - mysql-root-password
      - rstudio-cbaker-password
    restart: always
    volumes:
      - ./prototype/pfproto:/home/cbaker/pfproto

secrets:

  mysql-root-password:
    file: ./secrets/MYSQL_ROOT_PASSWORD
  auth0-client-secret:
    file: ./secrets/AUTH0_CLIENT_SECRET
  auth0-client-id:
    file: ./secrets/AUTH0_CLIENT_ID
  cookie-secret:
    file: ./secrets/COOKIE_SECRET
  pf-key:
    file: ./secrets/PF_KEY
  rstudio-cbaker-password:
    file: ./secrets/RSTUDIO_CBAKER_PASSWORD
