version: '3.1'

services:

  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./services/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  auth:
    build: ./services/shiny-auth0
    depends_on:
      - nginx
    ports:
      - 3000:3000
    secrets:
      - auth0-client-secret
      - auth0-client-id
      - cookie-secret
    restart: always

  mysql:
    image: mysql
    ports:
      - 3306:3306
    secrets:
      - mysql-root-password
    volumes:
      - ./services/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password

  shiny:
    depends_on:
      - auth
    build: ./shiny-server
    ports:
      - 3838:3838
    volumes:
      - ./shiny-server/shiny-server.conf:/etc/shiny-server/shiny-server.conf
    secrets:
      - mysql-root-password
    restart: always

  rstudio:
    image: rocker/tidyverse
    ports:
      - 8003:8787
    secrets:
      - mysql-root-password
    restart: always

secrets:
  mysql-root-password:
    file: ./services/secrets/MYSQL_ROOT_PASSWORD
  auth0-client-secret:
    file: ./services/secrets/AUTH0_CLIENT_SECRET
  auth0-client-id:
    file: ./services/secrets/AUTH0_CLIENT_ID
  cookie-secret:
    file: ./services/secrets/COOKIE_SECRET
