version: '3.1'

services:

  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./services/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  auth:
    build: ./services/shiny-auth0
    depends_on:
      - nginx
    ports:
      - 3000:3000
    secrets:
      - auth0-client-secret
      - auth0-client-id
      - cookie-secret
    restart: always

  mysql:
    image: mysql
    ports:
      - 3306:3306
    secrets:
      - mysql-root-password
    volumes:
      - ./services/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      # seen docker secretes section at https://hub.docker.com/_/mysql/
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password

  shiny:
    depends_on:
      - auth
    build: ./shiny-server/pfapp
    ports:
      - 3838:3838
    secrets:
      - mysql-root-password
    restart: always

  pfproto:
    depends_on:
      - mysql
    build: ./prototype/pfproto
    ports:
      - 8780:8787
    secrets:
      - pf-key
      - mysql-root-password
      - rstudio-root-password
    environment:
      # https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image#custom-use
      PASSWORD: /run/secrets/rstudio-root-password
    restart: always

secrets:
  mysql-root-password:
    file: ./services/secrets/MYSQL_ROOT_PASSWORD
  auth0-client-secret:
    file: ./services/secrets/AUTH0_CLIENT_SECRET
  auth0-client-id:
    file: ./services/secrets/AUTH0_CLIENT_ID
  cookie-secret:
    file: ./services/secrets/COOKIE_SECRET
  pf-key:
    file: ./services/secrets/PF_KEY
  rstudio-root-password:
    file: ./services/secrets/RSTUDIO_ROOT_PASSWORD
