version: '3.1'

services:

  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./services/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  auth:
    build: ./services/shiny-auth0
    depends_on:
      - nginx
    ports:
      - 3000:3000
    secrets:
      - auth0-client-secret
      - auth0-client-id
      - cookie-secret
    # just for dev:
    volumes:
      - ./services/shiny-auth0/.env:/shiny-auth0/.env
    restart: always

  mysql:
    image: mysql
    secrets:
      - mysql-root-password
    volumes:
      - ./services/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      # see docker secrets section at https://hub.docker.com/_/mysql/
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: pf_dev

  shiny:
    depends_on:
      - auth
    build: ./shiny-server/pfapp
    secrets:
      - mysql-root-password
    restart: always

  pfproto:
    depends_on:
      - mysql
    build: ./prototype/pfproto
    ports:
      - 8780:8787
    secrets:
      - pf-key
      - mysql-root-password
      - rstudio-cbaker-password
    restart: always
    volumes:
      - ./prototype/pfproto:/home/cbaker/pfproto

secrets:
  mysql-root-password:
    file: ./services/secrets/MYSQL_ROOT_PASSWORD
  auth0-client-secret:
    file: ./services/secrets/AUTH0_CLIENT_SECRET
  auth0-client-id:
    file: ./services/secrets/AUTH0_CLIENT_ID
  cookie-secret:
    file: ./services/secrets/COOKIE_SECRET
  pf-key:
    file: ./services/secrets/PF_KEY
  rstudio-cbaker-password:
    file: ./services/secrets/RSTUDIO_CBAKER_PASSWORD
