FROM rocker/tidyverse

# install general deps and shiny server
RUN apt-get update && apt-get install -y \
    sudo \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libxt-dev \
    libxml2-dev \
    libcairo2-dev \
    libsqlite-dev \
    libmariadbd-dev \
    libmariadb-client-lgpl-dev \
    libpq-dev \
    default-jre \
    default-jdk \
    libssh2-1-dev && \
    R CMD javareconf && \
    apt-get install -y r-cran-rjava && \
    wget --no-verbose https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/VERSION -O "version.txt" && \
    VERSION=$(cat version.txt)  && \
    wget --no-verbose "https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/shiny-server-$VERSION-amd64.deb" -O ss-latest.deb && \
    gdebi -n ss-latest.deb && \
    rm -f version.txt ss-latest.deb && \
    R -e "install.packages(c('shiny', 'rmarkdown'), repos='https://cran.rstudio.com/')" && \
    cp -R /usr/local/lib/R/site-library/shiny/examples/* /srv/shiny-server/ && \
    rm -rf /var/lib/apt/lists/* && \
    wget https://raw.githubusercontent.com/rocker-org/shiny/master/shiny-server.sh -O /usr/bin/shiny-server.sh && \
    chmod +x /usr/bin/shiny-server.sh

# copy shiny app code and shiny server config into container
COPY . /srv/shiny-server/sample-apps/pfapp
COPY ./inst/config/shiny-server.conf /etc/shiny-server/shiny-server.conf

# install deps of r package (app code) then install package
RUN cd /srv/shiny-server/sample-apps/pfapp && \
  Rscript -e "devtools::install_deps(repos = 'https://mran.microsoft.com/snapshot/2018-02-20')" && \
  Rscript -e "devtools::install()"

EXPOSE 3838

CMD /usr/bin/shiny-server.sh
